image: registry.gitlab.com/freepascal.org/fpc/source/debian-buster-x86_64

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - fpc tests.pas

unit-test-job:
  stage: test
  script:
    - ./tests
